title: Sindarin Programming Language
description: A statically-typed procedural language that compiles to C
url: "https://sindarinsdk.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

sass:
  sass_dir: _sass
  style: compressed

permalink: pretty

defaults:
  - scope:
      path: "docs"
    values:
      layout: page
      section: docs
      render_with_liquid: false
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile.lock
  - Makefile
  - README.md
  - node_modules/
  - vendor/

plugins:
  - jekyll-seo-tag
